version: '3.8'
services:
  php:
    image: php:8.1-fpm
    volumes:
      - .:/var/www
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - .:/var/www
    depends_on:
      - php
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appPuntoDeventa
  redis:
    image: redis:latest
  node:
    image: node:16
    volumes:
      - .:/var/www
